import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/Navbar'
import Provider from '@/components/provider/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'GGWTW',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <div className='space-y-2'>
            <Navbar />
            {children}
          </div>
        </body>
      </Provider>
    </html>
  )
}
